Refactor GitHub Actions workflow to simplify test setup
- Comment out redundant zsh-dotfiles-prep and chezmoi installation steps
- Streamline asdf version manager installation
- Remove verbose debugging and commented-out commands

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -56,73 +56,78 @@ jobs:
             echo "~/.local/bin" >> $GITHUB_PATH
             export PATH="~/.bin:~/bin:~/.local/bin:$PATH"
 
-            wget https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer
-            chmod +x zsh-dotfiles-prereq-installer
-            retry -t 4  -- ./zsh-dotfiles-prereq-installer --debug
+            # wget https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer
+            # chmod +x zsh-dotfiles-prereq-installer
+            # retry -t 4  -- ./zsh-dotfiles-prereq-installer --debug
 
-            # curl -fsSL https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer | bash -s -- --debug
+            brew install ./Formula/asdf@0.11.2.rb
+            brew unlink asdf
+            brew link --overwrite asdf@0.11.2
+            asdf --version
 
-      - name: Rerun zsh-dotfiles-prep
-        env:
-          ZSH_DOTFILES_PREP_CI: 1
-          ZSH_DOTFILES_PREP_DEBUG: 1
-          # NOTE: Skip Brew bundle for now, speed up tests
-          ZSH_DOTFILES_PREP_GITHUB_USER: bossjones
-          ZSH_DOTFILES_PREP_SKIP_BREW_BUNDLE: 1
-        run: |
-            # brew tap homebrew/cask || true
-            # brew tap homebrew/core || true
-            brew tap schniz/tap || true
-            brew install wget || true
-            brew install curl || true
-            brew install go || true
-            brew install trash || true
 
-            echo "~/bin" >> $GITHUB_PATH
-            echo "~/.bin" >> $GITHUB_PATH
-            echo "~/.local/bin" >> $GITHUB_PATH
-            export PATH="~/.bin:~/bin:~/.local/bin:$PATH"
 
-            wget https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer
-            chmod +x zsh-dotfiles-prereq-installer
-            retry -t 4  -- ./zsh-dotfiles-prereq-installer --debug
+      # - name: Rerun zsh-dotfiles-prep
+      #   env:
+      #     ZSH_DOTFILES_PREP_CI: 1
+      #     ZSH_DOTFILES_PREP_DEBUG: 1
+      #     # NOTE: Skip Brew bundle for now, speed up tests
+      #     ZSH_DOTFILES_PREP_GITHUB_USER: bossjones
+      #     ZSH_DOTFILES_PREP_SKIP_BREW_BUNDLE: 1
+      #   run: |
+      #       # brew tap homebrew/cask || true
+      #       # brew tap homebrew/core || true
+      #       brew tap schniz/tap || true
+      #       brew install wget || true
+      #       brew install curl || true
+      #       brew install go || true
+      #       brew install trash || true
 
-            # curl -fsSL https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer | bash -s -- --debug
+      #       echo "~/bin" >> $GITHUB_PATH
+      #       echo "~/.bin" >> $GITHUB_PATH
+      #       echo "~/.local/bin" >> $GITHUB_PATH
+      #       export PATH="~/.bin:~/bin:~/.local/bin:$PATH"
 
-      - name: full chezmoi install
-        env:
-          ZSH_DOTFILES_PREP_CI: 1
-          ZSH_DOTFILES_PREP_DEBUG: 1
-          # NOTE: Skip Brew bundle for now, speed up tests
-          ZSH_DOTFILES_PREP_GITHUB_USER: bossjones
-          ZSH_DOTFILES_PREP_SKIP_BREW_BUNDLE: 1
-        run: |
-          # set -x;pwd
-          # set -x;ls -lta
-          # set -x;ls -lta ~/.bin
-          # set +x
+      #       wget https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer
+      #       chmod +x zsh-dotfiles-prereq-installer
+      #       retry -t 4  -- ./zsh-dotfiles-prereq-installer --debug
 
-          echo "~/bin" >> $GITHUB_PATH
-          echo "~/.bin" >> $GITHUB_PATH
-          echo "~/.local/bin" >> $GITHUB_PATH
-          export PATH="~/.bin:~/bin:~/.local/bin:$PATH"
-          # set -x;which chezmoi
-          # set -x;whence chezmoi
-          # set +x
+      #       # curl -fsSL https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer | bash -s -- --debug
 
-          retry -t 4  -- ~/.bin/chezmoi init -R --debug -v --apply --force --source=.
+      # - name: full chezmoi install
+      #   env:
+      #     ZSH_DOTFILES_PREP_CI: 1
+      #     ZSH_DOTFILES_PREP_DEBUG: 1
+      #     # NOTE: Skip Brew bundle for now, speed up tests
+      #     ZSH_DOTFILES_PREP_GITHUB_USER: bossjones
+      #     ZSH_DOTFILES_PREP_SKIP_BREW_BUNDLE: 1
+      #   run: |
+      #     # set -x;pwd
+      #     # set -x;ls -lta
+      #     # set -x;ls -lta ~/.bin
+      #     # set +x
 
-          retry -t 4  -- post-install-chezmoi
+      #     echo "~/bin" >> $GITHUB_PATH
+      #     echo "~/.bin" >> $GITHUB_PATH
+      #     echo "~/.local/bin" >> $GITHUB_PATH
+      #     export PATH="~/.bin:~/bin:~/.local/bin:$PATH"
+      #     # set -x;which chezmoi
+      #     # set -x;whence chezmoi
+      #     # set +x
 
-          export LUNARVIM_LOG_LEVEL="debug"
-          export LV_BRANCH="release-1.3/neovim-0.9"
-          curl -s "https://raw.githubusercontent.com/LunarVim/LunarVim/${LV_BRANCH}/utils/installer/install.sh" | bash -s -- --install-dependencies -y
+      #     retry -t 4  -- ~/.bin/chezmoi init -R --debug -v --apply --force --source=.
 
-          # Install asdf v0.11.2 and verify version
-          brew install ./Formula/asdf@0.11.2.rb
-          brew unlink asdf
-          brew link --overwrite asdf@0.11.2
-          asdf --version
+      #     retry -t 4  -- post-install-chezmoi
+
+      #     export LUNARVIM_LOG_LEVEL="debug"
+      #     export LV_BRANCH="release-1.3/neovim-0.9"
+      #     curl -s "https://raw.githubusercontent.com/LunarVim/LunarVim/${LV_BRANCH}/utils/installer/install.sh" | bash -s -- --install-dependencies -y
+
+      #     # Install asdf v0.11.2 and verify version
+      #     brew install ./Formula/asdf@0.11.2.rb
+      #     brew unlink asdf
+      #     brew link --overwrite asdf@0.11.2
+      #     asdf --version
 
       - name: pytest
         run: |
