Update GitHub Actions workflow and asdf Homebrew formula
- Refactor tests.yml to use Homebrew setup and test-bot actions
- Simplify asdf installation process
- Rename AsdfAT0112 class to AsdfAT01112 in Homebrew formula
- Remove commented-out and redundant workflow steps

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -31,43 +31,40 @@ jobs:
           go-version: '1.20.5' # The Go version to download (if necessary) and use.
       - run: go version
 
+      - name: Set up Homebrew
+        id: set-up-homebrew
+        uses: Homebrew/actions/setup-homebrew@master
 
+      - name: Cache Homebrew Bundler RubyGems
+        id: cache
+        uses: actions/cache@v3
+        with:
+          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
+          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
+          restore-keys: ${{ runner.os }}-rubygems-
 
-      - name: brew taps
+      - name: Install Homebrew Bundler RubyGems
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: brew install-bundler-gems
+
+      - run: brew test-bot --only-cleanup-before
+
+      - run: brew test-bot --only-setup
+
+      - run: brew test-bot --only-tap-syntax
+
+      - name: try installing bossjones/asdf-versions/asdf@0.11.2
         run: |
-            brew tap schniz/tap || true
+          brew install --verbose bossjones/asdf-versions/asdf@0.11.2
+          # brew unlink asdf
+          # brew link --overwrite asdf@0.11.2
+          asdf --version
 
-      - name: Run zsh-dotfiles-prep
-        env:
-          ZSH_DOTFILES_PREP_CI: 1
-          ZSH_DOTFILES_PREP_DEBUG: 1
-          # NOTE: Skip Brew bundle for now, speed up tests
-          ZSH_DOTFILES_PREP_GITHUB_USER: bossjones
-          ZSH_DOTFILES_PREP_SKIP_BREW_BUNDLE: 1
-        run: |
-            brew tap schniz/tap || true
-            brew install wget || true
-            brew install curl || true
-            brew install kadwanev/brew/retry || true
-            brew install go || true
+      # - name: brew taps
+      #   run: |
+      #       brew tap schniz/tap || true
 
-            echo "~/bin" >> $GITHUB_PATH
-            echo "~/.bin" >> $GITHUB_PATH
-            echo "~/.local/bin" >> $GITHUB_PATH
-            export PATH="~/.bin:~/bin:~/.local/bin:$PATH"
-
-            # wget https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer
-            # chmod +x zsh-dotfiles-prereq-installer
-            # retry -t 4  -- ./zsh-dotfiles-prereq-installer --debug
-
-            brew install ./Formula/asdf@0.11.2.rb
-            brew unlink asdf
-            brew link --overwrite asdf@0.11.2
-            asdf --version
-
-
-
-      # - name: Rerun zsh-dotfiles-prep
+      # - name: Run zsh-dotfiles-prep
       #   env:
       #     ZSH_DOTFILES_PREP_CI: 1
       #     ZSH_DOTFILES_PREP_DEBUG: 1
@@ -75,59 +72,89 @@ jobs:
       #     ZSH_DOTFILES_PREP_GITHUB_USER: bossjones
       #     ZSH_DOTFILES_PREP_SKIP_BREW_BUNDLE: 1
       #   run: |
-      #       # brew tap homebrew/cask || true
-      #       # brew tap homebrew/core || true
       #       brew tap schniz/tap || true
       #       brew install wget || true
       #       brew install curl || true
+      #       brew install kadwanev/brew/retry || true
       #       brew install go || true
-      #       brew install trash || true
 
       #       echo "~/bin" >> $GITHUB_PATH
       #       echo "~/.bin" >> $GITHUB_PATH
       #       echo "~/.local/bin" >> $GITHUB_PATH
       #       export PATH="~/.bin:~/bin:~/.local/bin:$PATH"
 
-      #       wget https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer
-      #       chmod +x zsh-dotfiles-prereq-installer
-      #       retry -t 4  -- ./zsh-dotfiles-prereq-installer --debug
+      #       # wget https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer
+      #       # chmod +x zsh-dotfiles-prereq-installer
+      #       # retry -t 4  -- ./zsh-dotfiles-prereq-installer --debug
 
-      #       # curl -fsSL https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer | bash -s -- --debug
+      #       brew install ./Formula/asdf@0.11.2.rb
+      #       brew unlink asdf
+      #       brew link --overwrite asdf@0.11.2
+      #       asdf --version
 
-      # - name: full chezmoi install
-      #   env:
-      #     ZSH_DOTFILES_PREP_CI: 1
-      #     ZSH_DOTFILES_PREP_DEBUG: 1
-      #     # NOTE: Skip Brew bundle for now, speed up tests
-      #     ZSH_DOTFILES_PREP_GITHUB_USER: bossjones
-      #     ZSH_DOTFILES_PREP_SKIP_BREW_BUNDLE: 1
-      #   run: |
-      #     # set -x;pwd
-      #     # set -x;ls -lta
-      #     # set -x;ls -lta ~/.bin
-      #     # set +x
 
-      #     echo "~/bin" >> $GITHUB_PATH
-      #     echo "~/.bin" >> $GITHUB_PATH
-      #     echo "~/.local/bin" >> $GITHUB_PATH
-      #     export PATH="~/.bin:~/bin:~/.local/bin:$PATH"
-      #     # set -x;which chezmoi
-      #     # set -x;whence chezmoi
-      #     # set +x
 
-      #     retry -t 4  -- ~/.bin/chezmoi init -R --debug -v --apply --force --source=.
+      # # - name: Rerun zsh-dotfiles-prep
+      # #   env:
+      # #     ZSH_DOTFILES_PREP_CI: 1
+      # #     ZSH_DOTFILES_PREP_DEBUG: 1
+      # #     # NOTE: Skip Brew bundle for now, speed up tests
+      # #     ZSH_DOTFILES_PREP_GITHUB_USER: bossjones
+      # #     ZSH_DOTFILES_PREP_SKIP_BREW_BUNDLE: 1
+      # #   run: |
+      # #       # brew tap homebrew/cask || true
+      # #       # brew tap homebrew/core || true
+      # #       brew tap schniz/tap || true
+      # #       brew install wget || true
+      # #       brew install curl || true
+      # #       brew install go || true
+      # #       brew install trash || true
 
-      #     retry -t 4  -- post-install-chezmoi
+      # #       echo "~/bin" >> $GITHUB_PATH
+      # #       echo "~/.bin" >> $GITHUB_PATH
+      # #       echo "~/.local/bin" >> $GITHUB_PATH
+      # #       export PATH="~/.bin:~/bin:~/.local/bin:$PATH"
 
-      #     export LUNARVIM_LOG_LEVEL="debug"
-      #     export LV_BRANCH="release-1.3/neovim-0.9"
-      #     curl -s "https://raw.githubusercontent.com/LunarVim/LunarVim/${LV_BRANCH}/utils/installer/install.sh" | bash -s -- --install-dependencies -y
+      # #       wget https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer
+      # #       chmod +x zsh-dotfiles-prereq-installer
+      # #       retry -t 4  -- ./zsh-dotfiles-prereq-installer --debug
 
-      #     # Install asdf v0.11.2 and verify version
-      #     brew install ./Formula/asdf@0.11.2.rb
-      #     brew unlink asdf
-      #     brew link --overwrite asdf@0.11.2
-      #     asdf --version
+      # #       # curl -fsSL https://raw.githubusercontent.com/bossjones/zsh-dotfiles-prep/main/bin/zsh-dotfiles-prereq-installer | bash -s -- --debug
+
+      # # - name: full chezmoi install
+      # #   env:
+      # #     ZSH_DOTFILES_PREP_CI: 1
+      # #     ZSH_DOTFILES_PREP_DEBUG: 1
+      # #     # NOTE: Skip Brew bundle for now, speed up tests
+      # #     ZSH_DOTFILES_PREP_GITHUB_USER: bossjones
+      # #     ZSH_DOTFILES_PREP_SKIP_BREW_BUNDLE: 1
+      # #   run: |
+      # #     # set -x;pwd
+      # #     # set -x;ls -lta
+      # #     # set -x;ls -lta ~/.bin
+      # #     # set +x
+
+      # #     echo "~/bin" >> $GITHUB_PATH
+      # #     echo "~/.bin" >> $GITHUB_PATH
+      # #     echo "~/.local/bin" >> $GITHUB_PATH
+      # #     export PATH="~/.bin:~/bin:~/.local/bin:$PATH"
+      # #     # set -x;which chezmoi
+      # #     # set -x;whence chezmoi
+      # #     # set +x
+
+      # #     retry -t 4  -- ~/.bin/chezmoi init -R --debug -v --apply --force --source=.
+
+      # #     retry -t 4  -- post-install-chezmoi
+
+      # #     export LUNARVIM_LOG_LEVEL="debug"
+      # #     export LV_BRANCH="release-1.3/neovim-0.9"
+      # #     curl -s "https://raw.githubusercontent.com/LunarVim/LunarVim/${LV_BRANCH}/utils/installer/install.sh" | bash -s -- --install-dependencies -y
+
+      # #     # Install asdf v0.11.2 and verify version
+      # #     brew install ./Formula/asdf@0.11.2.rb
+      # #     brew unlink asdf
+      # #     brew link --overwrite asdf@0.11.2
+      # #     asdf --version
 
       - name: pytest
         run: |
